# Generated by Django 6.0.3 on 2026-06-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingentry',
            name='chart_image',
            field=models.ImageField(blank=True, null=True, upload_to='writing/charts/'),
        ),
        migrations.AddField(
            model_name='writingentry',
            name='chart_type',
            field=models.CharField(blank=True, choices=[('', '不选择'), ('line', '折线图'), ('bar', '柱状图'), ('pie', '饼图'), ('table', '表格'), ('map', '地图'), ('process', '流程图'), ('mixed', '混合图'), ('other', '其他')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='writinghighlightword',
            name='word',
            field=models.CharField(max_length=255),
        ),
    ]
