# Generated by Django 6.0.3 on 2026-05-12 13:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryDictationWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='英文单词')),
                ('meaning_cn', models.CharField(blank=True, default='', max_length=255, verbose_name='中文意思')),
                ('phonetic', models.CharField(blank=True, default='', max_length=100, verbose_name='音标')),
                ('example_sentence', models.TextField(blank=True, default='', verbose_name='例句')),
                ('audio_url', models.URLField(blank=True, default='', verbose_name='音频 URL')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '小学听写单词',
                'verbose_name_plural': '小学听写单词',
                'db_table': 'primary_dictation_word',
                'ordering': ['word_set', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrimaryWordSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='词表名称')),
                ('grade', models.CharField(choices=[('g1', '一年级'), ('g2', '二年级'), ('g3', '三年级'), ('g4', '四年级'), ('g5', '五年级'), ('g6', '六年级')], default='g3', max_length=20, verbose_name='年级')),
                ('term', models.CharField(choices=[('upper', '上册'), ('lower', '下册'), ('other', '其他')], default='upper', max_length=20, verbose_name='学期')),
                ('unit', models.CharField(blank=True, default='', max_length=100, verbose_name='单元')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '小学听写词表',
                'verbose_name_plural': '小学听写词表',
                'db_table': 'primary_word_set',
                'ordering': ['grade', 'term', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrimaryDictationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='总数')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='正确数')),
                ('wrong_count', models.PositiveIntegerField(default=0, verbose_name='错误数')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('word_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='primary_dictation.primarywordset', verbose_name='词表')),
            ],
            options={
                'verbose_name': '小学听写记录',
                'verbose_name_plural': '小学听写记录',
                'db_table': 'primary_dictation_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PrimaryDictationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(blank=True, default='', max_length=100, verbose_name='学生答案')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='primary_dictation.primarydictationsession', verbose_name='听写记录')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary_dictation.primarydictationword', verbose_name='单词')),
            ],
            options={
                'verbose_name': '小学听写结果',
                'verbose_name_plural': '小学听写结果',
                'db_table': 'primary_dictation_result',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='primarydictationword',
            name='word_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='primary_dictation.primarywordset', verbose_name='所属词表'),
        ),
        migrations.AlterUniqueTogether(
            name='primarydictationword',
            unique_together={('word_set', 'word')},
        ),
    ]
