# Generated by Django 5.2.12 on 2026-03-19 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('phonetic', models.CharField(blank=True, max_length=100)),
                ('meaning_cn', models.CharField(blank=True, max_length=255)),
                ('part_of_speech', models.CharField(blank=True, max_length=50)),
                ('example_sentence', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('difficulty', models.PositiveSmallIntegerField(default=3)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('wrongbook', 'Wrong Book'), ('import', 'Import')], default='manual', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('tts_text', models.CharField(blank=True, max_length=255)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('memory_level', models.PositiveSmallIntegerField(default=0)),
                ('is_forgotten', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='vocab.wordtag')),
            ],
            options={
                'ordering': ['word'],
                'unique_together': {('user', 'word')},
            },
        ),
    ]
