# Generated by Django 6.0.3 on 2026-04-07 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(choices=[('part1', 'Part 1'), ('part2', 'Part 2'), ('part3', 'Part 3'), ('general', 'General')], default='general', max_length=20)),
                ('question_text', models.TextField()),
                ('reference_answer', models.TextField(blank=True)),
                ('reference_audio_url', models.URLField(blank=True)),
                ('keywords', models.TextField(blank=True, help_text='英文逗号分隔')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='speaking_attempts/')),
                ('transcript', models.TextField(blank=True)),
                ('duration_sec', models.FloatField(default=0)),
                ('score_overall', models.FloatField(default=0)),
                ('score_similarity', models.FloatField(default=0)),
                ('score_keywords', models.FloatField(default=0)),
                ('score_length', models.FloatField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='speaking.speakingquestion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
