# Generated by Django 6.0.3 on 2026-05-06 07:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='话题标题')),
                ('part', models.CharField(choices=[('part1', 'Part 1'), ('part2', 'Part 2'), ('part3', 'Part 3')], default='part1', max_length=20, verbose_name='雅思部分')),
                ('description', models.TextField(blank=True, default='', verbose_name='话题说明')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '口语话题',
                'verbose_name_plural': '口语话题',
                'db_table': 'speaking_topic',
                'ordering': ['part', 'sort_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='speakingquestion',
            options={'ordering': ['topic', 'sort_order', 'id'], 'verbose_name': '口语问题', 'verbose_name_plural': '口语问题'},
        ),
        migrations.RemoveField(
            model_name='speakingquestion',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='speakingquestion',
            name='note',
        ),
        migrations.RemoveField(
            model_name='speakingquestion',
            name='reference_answer',
        ),
        migrations.RemoveField(
            model_name='speakingquestion',
            name='reference_audio_url',
        ),
        migrations.RemoveField(
            model_name='speakingquestion',
            name='title',
        ),
        migrations.RemoveField(
            model_name='speakingquestion',
            name='user',
        ),
        migrations.AddField(
            model_name='speakingquestion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='speakingquestion',
            name='key_points',
            field=models.TextField(blank=True, default='', verbose_name='答题要点'),
        ),
        migrations.AddField(
            model_name='speakingquestion',
            name='sample_answer',
            field=models.TextField(blank=True, default='', verbose_name='参考回答'),
        ),
        migrations.AddField(
            model_name='speakingquestion',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='speakingquestion',
            name='useful_expressions',
            field=models.TextField(blank=True, default='', verbose_name='有用表达'),
        ),
        migrations.AlterField(
            model_name='speakingquestion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='speakingquestion',
            name='question_text',
            field=models.TextField(verbose_name='问题内容'),
        ),
        migrations.AlterField(
            model_name='speakingquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterModelTable(
            name='speakingquestion',
            table='speaking_question',
        ),
        migrations.CreateModel(
            name='SpeakingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, default='', verbose_name='回答文本')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='speaking/answers/%Y/%m/%d/', verbose_name='回答录音')),
                ('score_overall', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='总分')),
                ('score_fluency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='流利度')),
                ('score_pronunciation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='发音')),
                ('score_grammar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='语法')),
                ('score_vocab', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='词汇')),
                ('feedback', models.TextField(blank=True, default='', verbose_name='反馈')),
                ('corrected_answer', models.TextField(blank=True, default='', verbose_name='优化后回答')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='录音时长秒数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='speaking.speakingquestion', verbose_name='所属问题')),
            ],
            options={
                'verbose_name': '口语回答记录',
                'verbose_name_plural': '口语回答记录',
                'db_table': 'speaking_answer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='speakingquestion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='speaking.speakingtopic', verbose_name='所属话题'),
        ),
        migrations.DeleteModel(
            name='SpeakingAttempt',
        ),
    ]
