# Generated by Codex on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speaking", "0002_speakingtopic_alter_speakingquestion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakingquestion",
            name="memorized_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="背过时间"),
        ),
    ]
