# Generated by Django 6.0.3 on 2026-05-16 10:58

import jianpu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JianpuScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='未命名歌曲', max_length=200, verbose_name='歌曲名称')),
                ('key', models.CharField(default='1=C', max_length=20, verbose_name='调号')),
                ('time_signature', models.CharField(default='4/4', max_length=20, verbose_name='拍号')),
                ('tempo', models.IntegerField(default=90, verbose_name='速度')),
                ('score_data', models.JSONField(default=jianpu.models.default_score_data, verbose_name='简谱数据')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '简谱',
                'verbose_name_plural': '简谱',
                'ordering': ['-updated_at'],
            },
        ),
    ]
