# Generated by Django 6.0.3 on 2026-03-27 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhraseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_text', models.TextField()),
                ('chinese_text', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('writing', 'Writing'), ('speaking', 'Speaking'), ('general', 'General')], default='general', max_length=20)),
                ('usage_note', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
