# Generated by Codex on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synonyms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="synonymitem",
            name="comparison_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="synonymitem",
            name="fixed_sentence",
            field=models.TextField(blank=True),
        ),
    ]
