# Generated by Codex on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synonyms", "0002_synonymitem_comparison_note_and_fixed_sentence"),
    ]

    operations = [
        migrations.AddField(
            model_name="synonymitem",
            name="usage_context",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
