# Generated by Codex on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synonyms", "0003_synonymitem_usage_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="synonymentry",
            name="is_learned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="synonymentry",
            name="review_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="synonymentry",
            name="review_correct",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="synonymentry",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
